#!/usr/bin/env node

'use strict';

var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');

var host = '127.0.0.1';
var port = 3030;
var url = host + ':' + port.toString();

var config = {
   host: host,
   port: port,
   devtool: '#eval-source-map',
   entry: [
      'webpack-dev-server/client?' + url,
      './index'
   ],
   output: {
      path: __dirname + '/dist',
      filename: 'bundle.js',
      publicPath: '/dist/'
   },
   plugins: [
      new webpack.NoErrorsPlugin()
   ],
   resolve: {
      modulesDirectories: [
         'node_modules',
         'web_modules'
      ],
      extensions: [
         '',
         '.js',
         '.jsx',
         '.json',
         '.styl'
      ]
   },
   module: {
      loaders: [
         { test: /\.jsx?$/, loader: 'jsx?harmony' },
         { test: /\.json$/, loader: 'json' },
         { test: /\.styl$/, loader: 'style!css!autoprefixer!stylus' },
         { test: /\.css$/, loader: 'style!css!autoprefixer' },
         { test: /\.png$/, loader: 'url?limit=20480&mimetype=image/png' },
         { test: /\.jpg$/, loader: 'file' }
      ]
   }
};

var server = new WebpackDevServer(webpack(config), {
   publicPath: config.output.publicPath,
   stats: { colors: true },
});

server.listen(
   config.port, config.host,
   function (err, result) {
      if (err) {
         console.log(err);
      }
      else {
         console.log('Listening at: http://' + url);
      }
   }
);
