#!/usr/bin/env node

'use strict';

var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config.devel');
var pkg = require('./package.json');

var port = pkg.config.port || 3000;
var server = new WebpackDevServer(webpack(config), {
   publicPath: config.output.publicPath,
   stats: { colors: true },
});

server.listen(
   port,
   'localhost',
   function (err, result) {
      if (err) {
         console.log(err);
      }
      else {
         console.log('Listening at:');
         console.log('   http://localhost:' + port);
         console.log('   http://localhost:' + port + '/webpack-dev-server/\n');
      }
   }
);
