#!/bin/bash
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )

NODE_ENV=test node --harmony ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha
cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
